name: 'Call a reusable workflow and use outputs'

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  call-reusable-workflow:
    name: 'Call reusable workflow'
    uses: ./.github/workflows/toBeReused.yaml
    #secrets: inherit
  
  output-job:
    runs-on: ubuntu-latest
    needs: deploy-global-infrastructure
    steps:
     - run: |
        echo ${{ needs.deploy-global-infrastructure }} 
        echo ${{ needs.deploy-global-infrastructure.outputs }}
        echo ${{ needs.deploy-global-infrastructure.outputs.AcrName }}
        echo ${{ needs.deploy-global-infrastructure.outputs.AcrResourceGroup }}
