name: 'Call a reusable workflow and use outputs'

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  call-reusable-workflow:
    name: 'Call reusable workflow'
    uses: ./.github/workflows/toBeReused.yml
    #secrets: inherit
  
  output-job:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow
    steps:
     - run: |
        echo ${{ needs.call-reusable-workflow.outputs.output1 }}
        echo ${{ needs.call-reusable-workflow.outputs.output2 }}
